# Generated by Django 3.2.13 on 2022-08-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='cca4a132-fc3c-4ad5-9b42-874c0af5686f', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
