# Generated by Django 3.2.13 on 2022-08-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='ed624123-6651-49a9-b47c-aaefb46a7e61', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
