# Generated by Django 3.2.13 on 2022-08-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='42d7e902-42b5-4706-bb94-fdd12bdc7019', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='myuser',
            table='auth_user',
        ),
    ]
