# Generated by Django 3.2.13 on 2022-08-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='19e24686-2be3-4c9b-80df-6cd702cae8ea', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
