# Generated by Django 3.2.16 on 2023-02-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='15c4bcba-f621-4466-b437-f0da134930d1', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
